# Generated by Django 5.0.1 on 2024-01-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1) Категория', 'verbose_name_plural': '1) Категории'},
        ),
    ]
