# Generated by Django 5.0.1 on 2024-01-10 07:24

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': '2) Добавить Бренд',
                'verbose_name_plural': '2) Добавить Бренды',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название коллекции')),
            ],
            options={
                'verbose_name': '3) Добавить Коллекцию',
                'verbose_name_plural': '3) Добавить Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': '5) Добавить Цены',
                'verbose_name_plural': '5) Добавить Цены',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Информационный текст')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='sale/', verbose_name='Банерная фотография')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('price_sale', models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой(если есть скидка)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.brand', verbose_name='Выберите бренд в которую входит данный продукт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.categoryadd', verbose_name='Выберите категорию в которую входит данный продукт')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collection', to='products.collection', verbose_name='Выберите коллекцию в которую входит данный продукт')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.price', verbose_name='Выберите цену в которую входит данный продукт')),
            ],
            options={
                'verbose_name': '5) Добавить Одежду',
                'verbose_name_plural': '5) Добавить Одежду',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='sale/', verbose_name='Фотографии одежды')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product')),
            ],
            options={
                'verbose_name': '3) Добавить Фотографию',
                'verbose_name_plural': '3) Добавить Фотографию',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите цвет ')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.product')),
            ],
            options={
                'verbose_name': '1) Добавить Цвет',
                'verbose_name_plural': '1) Добавить Цвета',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Укажите Размер в письменном ввиде полностью')),
                ('al', models.CharField(max_length=2, verbose_name='Укажите Размер в письменном ввиде сокращенно ')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='products.product')),
            ],
            options={
                'verbose_name': '2) Добавить Размер',
                'verbose_name_plural': '2) Добавить Размеры',
            },
        ),
    ]
