# Generated by Django 5.0.1 on 2024-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_collection_price_product_image_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название под категории')),
            ],
            options={
                'verbose_name': '2) Добавить Вторичную Категорию',
                'verbose_name_plural': '2) Добавить Вторичную Категорию',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '3) Добавить Бренд', 'verbose_name_plural': '3) Добавить Бренды'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '4) Добавить Коллекцию', 'verbose_name_plural': '4) Добавить Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '6) Добавить Одежду', 'verbose_name_plural': '6) Добавить Одежду'},
        ),
    ]
