# Generated by Django 5.0.1 on 2024-01-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_twoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_twoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_twoo', to='products.twocategory', verbose_name='Выберите вторичную категорию в которую входит данный продукт'),
        ),
    ]
