# Generated by Django 5.0.1 on 2024-01-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_twoo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Добавить Цвет', 'verbose_name_plural': 'Добавить Цвета'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Добавить Фотографию', 'verbose_name_plural': 'Добавить Фотографию'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Добавить Размер', 'verbose_name_plural': 'Добавить Размеры'},
        ),
    ]
