# Generated by Django 5.0.1 on 2024-01-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_color_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите цвет ')),
            ],
            options={
                'verbose_name': '6) Добавить Цвет',
                'verbose_name_plural': '6) Добавить Цвета',
            },
        ),
        migrations.CreateModel(
            name='SizeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Укажите Размер в письменном ввиде полностью')),
                ('al', models.CharField(max_length=2, verbose_name='Укажите Размер в письменном ввиде сокращенно ')),
            ],
            options={
                'verbose_name': '7) Добавить Размер',
                'verbose_name_plural': '7) Добавить Размеры',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '8) Добавить Одежду', 'verbose_name_plural': '8) Добавить Одежду'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='al',
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_ad', to='products.product'),
        ),
        migrations.AlterField(
            model_name='color',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.colorad'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_ad', to='products.sizead'),
        ),
    ]
