# Generated by Django 5.0.1 on 2024-01-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_colorad_sizead_alter_product_options_remove_size_al_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizead',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Укажите Размер в письменном ввиде полностью'),
        ),
    ]
