# Generated by Django 5.0.1 on 2024-01-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_indexproduct_indeximage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexproduct',
            options={'verbose_name': '9) Добавить Одежду для главной страницы', 'verbose_name_plural': '9) Добавить Одежду для главной страницы '},
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_input', to='products.product'),
        ),
    ]
