# Generated by Django 5.0.1 on 2024-01-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_indexproduct_options_alter_color_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.product'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_ad', to='products.colorad'),
        ),
    ]
