# Generated by Django 5.0.1 on 2024-01-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_color_settings_alter_color_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexproduct',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_index', to='products.brand', verbose_name='Выберите бренд в которую входит данный продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_index', to='products.categoryadd', verbose_name='Выберите категорию в которую входит данный продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexproduct',
            name='category_twoo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_twoo_index', to='products.twocategory', verbose_name='Выберите вторичную категорию в которую входит данный продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexproduct',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_collection_index', to='products.collection', verbose_name='Выберите коллекцию в которую входит данный продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexproduct',
            name='prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices_index', to='products.price', verbose_name='Выберите цену в которую входит данный продукт'),
            preserve_default=False,
        ),
    ]
