# Generated by Django 5.0.1 on 2024-01-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_coloradindex_sizeadindex_colorindex_sizeindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorindex',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_ad_index', to='products.categoryadd'),
        ),
        migrations.AlterField(
            model_name='sizeindex',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_ad_index', to='products.sizead'),
        ),
        migrations.DeleteModel(
            name='ColorAdIndex',
        ),
        migrations.DeleteModel(
            name='SizeAdIndex',
        ),
    ]
