# Generated by Django 5.0.1 on 2024-01-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_colorindex_title_alter_sizeindex_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorindex',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_ad_index', to='products.colorad'),
        ),
    ]
