# Generated by Django 5.0.1 on 2024-01-08 08:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter_images/', verbose_name='Изображение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='newsletter_attachments/', verbose_name='Вложение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отправить рассылку',
                'verbose_name_plural': 'Отправить рассылку',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Пользователи для рассылки',
                'verbose_name_plural': 'Пользователи для рассылки',
            },
        ),
    ]
