# Generated by Django 5.0.1 on 2024-01-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '3) Запросы на связи', 'verbose_name_plural': '3) Запросы на связь'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': '1) Отправить рассылку', 'verbose_name_plural': '1) Отправить рассылку'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '4) Отзыв', 'verbose_name_plural': '4) Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': '2) Пользователи для рассылки', 'verbose_name_plural': '2) Пользователи для рассылки'},
        ),
    ]
