# Generated by Django 5.0.1 on 2024-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_delete_telegramuser_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет товара')),
                ('size', models.CharField(max_length=255, verbose_name='Цвет товара')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': '3) Запросы на связи',
                'verbose_name_plural': '3) Запросы на связь',
            },
        ),
    ]
