# Generated by Django 5.0.1 on 2024-01-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_buy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'verbose_name': '1) Запросы на покупку товара', 'verbose_name_plural': '1) Запросы на покупку товарат'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '4) Запросы на связи', 'verbose_name_plural': '4) Запросы на связь'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': '2) Отправить рассылку', 'verbose_name_plural': '2) Отправить рассылку'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '5) Отзыв', 'verbose_name_plural': '5) Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': '3) Пользователи для рассылки', 'verbose_name_plural': '3) Пользователи для рассылки'},
        ),
        migrations.AlterField(
            model_name='buy',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размер товара'),
        ),
    ]
