# Generated by Django 5.0.1 on 2024-01-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Введите подзаголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Введите заголовок'),
        ),
    ]
