# Generated by Django 5.0.1 on 2024-01-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_lookbook_lookbookadd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookbook',
            options={'verbose_name': 'Образцы', 'verbose_name_plural': 'Образцы'},
        ),
    ]
