# Generated by Django 5.0.1 on 2024-01-08 07:05

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_lookbook_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='banner/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Баннер & Наши Бренды',
                'verbose_name_plural': 'Баннер & Наши Бренды ',
            },
        ),
        migrations.AlterModelOptions(
            name='lookbook',
            options={'verbose_name': 'Образцы & О нас', 'verbose_name_plural': 'Образцы & О нас '},
        ),
        migrations.CreateModel(
            name='BannerAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='brand/', verbose_name='Фотография')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_add', to='secondary.banner')),
            ],
            options={
                'verbose_name': 'Добавить фото образцов',
                'verbose_name_plural': 'Добавить фото образцов',
            },
        ),
    ]
