# Generated by Django 5.0.1 on 2024-01-08 12:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='team/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Имя')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Наша комманда',
                'verbose_name_plural': 'Наша комманда ',
            },
        ),
    ]
