# Generated by Django 5.0.1 on 2024-01-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_categoryadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryadd',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Нумерация'),
        ),
    ]
