# Generated by Django 5.0.1 on 2024-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categoryadd_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryadd',
            name='number',
            field=models.IntegerField(default=6, verbose_name='Нумерация'),
        ),
    ]
