# Generated by Django 5.0.1 on 2024-01-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_categoryadd_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryadd',
            name='number',
            field=models.CharField(default=6, max_length=255, verbose_name='Нумерация'),
        ),
    ]
