# Generated by Django 5.0.1 on 2024-01-08 05:00

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_categoryadd_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='sale/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Информационный текст')),
                ('date', models.DateTimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Cкидка',
                'verbose_name_plural': 'Cкидки',
            },
        ),
    ]
