# Generated by Django 5.0.1 on 2024-01-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Время окончания'),
        ),
    ]
