# Generated by Django 5.0.1 on 2024-01-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
