# Generated by Django 5.0.1 on 2024-01-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='sale',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
