# Generated by Django 5.0.1 on 2024-01-08 07:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_banner',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='blog_banner/', verbose_name='Фотография для баннера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='blog/', verbose_name='Фотография'),
        ),
    ]
