# Generated by Django 5.0.1 on 2024-01-08 11:56

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_blog_image_banner_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Девиз')),
            ],
            options={
                'verbose_name': 'Наш девиз',
                'verbose_name_plural': 'Наш девиз',
            },
        ),
        migrations.CreateModel(
            name='DevizAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='devis/', verbose_name='Фотография')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviiz', to='base.devis')),
            ],
            options={
                'verbose_name': 'Добавить фото для пункта Девиз',
                'verbose_name_plural': 'Добавить фото для пункта Девиз',
            },
        ),
    ]
