# Generated by Django 5.0.1 on 2024-01-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_devis_devizadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryadd',
            name='settings',
        ),
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name': '2) Наш девиз', 'verbose_name_plural': '2) Наш девиз'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Основная настройка', 'verbose_name_plural': '1) Основные настройки'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryAdd',
        ),
    ]
