# Generated by Django 5.0.1 on 2024-01-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_categoryadd_settings_alter_devis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '4) Новость', 'verbose_name_plural': '4) Новости'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '3) Cкидка', 'verbose_name_plural': '3) Cкидки'},
        ),
    ]
